### ISSUE TITLE
No rule / file: libraries/ghc-boot/stage0/build/GHC/PackageDb.hi

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#148] opened 2016-01-10 12:18 UTC
Here's the lastest issue the build on mac chokes on:

```
Error when running Shake build system:
* inplace/bin/ghc-pkg
* inplace/lib/bin/ghc-pkg
* .build/stage0/utils/ghc-pkg/build/Main.o
* libraries/ghc-boot/stage0/build/GHC/PackageDb.hi
Error, file does not exist and no rule available:
  libraries/ghc-boot/stage0/build/GHC/PackageDb.hi
```

**Comment by snowleopard** [comment] 2016-01-10 12:20
Argh. Sorry for breaking so many things, should have tested the `.build` stuff more rigorously.

**Comment by angerman** [comment] 2016-01-10 12:23
I'll just keep reporting. But this got me thinking, how about you use a `branch` for something like this next time, so `master` stays stable? I'm happy to test branches and report issues :) Just let me know which branch you want tested :D (travis and appveyor) builds will happen anyway, I assume.

**Comment by snowleopard** [comment] 2016-01-10 12:25
@angerman I agree, I'll follow that route next time I'm doing a potentially breaking change.

**Comment by snowleopard** [comment] 2016-01-10 12:40
I can reproduce this now, but the reason is unclear. Somehow `ghc -M` still points to `.hi` files in old build hierarchy. Here is the command line:
```
C:/msys/mingw64/bin/ghc.exe
-M
-hisuf hi
-osuf o
-hcsuf hc
-static
-hide-all-packages
-no-user-package-db
-package-db C:/msys/home/chEEtah/ghc/libraries/bootstrapping.conf
-package-id Cabal-1.23.0.0
-package-id base-4.8.0.0-38f91a7555d2f575c8807ba48f8f8c74
-package-id binary-0.8.0.0
-package-id bytestring-0.10.6.0-34350dee9a2300dc36aed53f30dfb244
-package-id containers-0.5.6.2-482fb2ad7079ecf2a7`3ae0d36f10634f
-package-id directory-1.2.2.0-3278bdbb50b7d45e81f377801f7fe4f6
-package-id filepath-1.4.0.0-0711b9d620e834224f620b655290b987
-package-id ghc-boot-8.1
-package-id process-1.2.3.0-a90544adc51cf15133cc92f593006f50
-i
-i.build/stage0/utils/ghc-pkg/build
-i.build/stage0/utils/ghc-pkg/build/autogen
-iutils/ghc-pkg
-I.build/stage0/utils/ghc-pkg/build
-I.build/stage0/utils/ghc-pkg/build/autogen
-IC:\msys\mingw64\lib\proce_ATSTvIqg2WXBzBH9rKyLH4\include
-IC:\msys\mingw64\lib\direc_99qvtH9mozB1bmqVxRYjwg\include
-IC:\msys\mingw64\lib\time_JXSg2wM2mStHlWvO55M2Ga\include
-IC:\msys\mingw64\lib\Win32_9y3u0frE63H1E2HTZUjJ63\include
-IC:\msys\mingw64\lib\bytes_6vj5EoliHgNHISHCVCb069\include
-IC:\msys\mingw64\lib\base_I5BErHzyOm07EBNpKBEeUv\include
-IC:\msys\mingw64\lib\integ_2aU3IZNMF9a7mQ0OzsZ0dS\include
-IC:\msys\mingw64\lib/include
-optP-include
-optP.build/stage0/utils/ghc-pkg/build/autogen/cabal_macros.h
-XHaskell2010
-odir .build/stage0/utils/ghc-pkg/build
-hidir .build/stage0/utils/ghc-pkg/build
-stubdir .build/stage0/utils/ghc-pkg/build
-rtsopts
-include-pkg-deps
-dep-makefile .build/stage0/utils/ghc-pkg/build/.hs-dependencies
-dep-suffix  utils/ghc-pkg/Main.hs .build/stage0/utils/ghc-pkg/build/Version.hs
```
I don't see where I screwed up: all paths seem to point to `.build`.
Still the produced `.hs-dependencies` file contains the following:
```
[...]
.build/stage0/utils/ghc-pkg/build/Main.o : libraries/Cabal/Cabal/stage0/build/Distribution/Simple/PackageIndex.hi
.build/stage0/utils/ghc-pkg/build/Main.o : libraries/ghc-boot/stage0/build/GHC/PackageDb.hi
.build/stage0/utils/ghc-pkg/build/Main.o : .build/stage0/utils/ghc-pkg/build/Version.hi
```
So, some paths are correct (`.build/stage0/utils/ghc-pkg/build/Version.hi`) but others are not (`libraries/ghc-boot/stage0/build/GHC/PackageDb.hi`).

**Comment by snowleopard** [comment] 2016-01-10 12:43
Within package dependency paths appear to be correct, but those referring to other packages in the system are broken.

**Comment by snowleopard** [comment] 2016-01-10 12:45
Here is a line from `libraries/bootstrapping.conf/Cabal-1.23.0.0.conf` that may be responsible:
```
import-dirs: C:\msys\home\chEEtah\ghc\libraries\Cabal\Cabal\stage0\build
```

**Comment by snowleopard** [comment] 2016-01-10 12:48
The only workaround I see without fixing `ghc-cabal` first is to post-process `.conf` files fixing the paths.

**Comment by snowleopard** [comment] 2016-01-10 14:26
Right. I pushed the fix. Let's see if this is enough to clean up the mess.

**Comment by snowleopard** [comment] 2016-01-10 15:24
OK, seems to pass CI.

**Closed by snowleopard** 2016-01-10 15:24 UTC
Labels: bug
