### ISSUE TITLE
Transient failure to build libHSrts.a

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#203] opened 2016-02-04 10:18 UTC
(Note, if relevant, that I'm using GHC from 2 days ago but shakeing from right now.)

    Error when running Shake build system:
    * .build/stage1/rts/build/libHSrts.a
    user error (Development.Shake.cmd, system command failed
    Command: C:/Neil/ghc/conf3/ghc/inplace/mingw/bin/ar.exe q .build/stage1/rts/build/libHSrts.a @C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\msys2-20150512\tmp\extra-file-504133661-1694121724
    Exit code: 1
    Stderr:
    C:/Neil/ghc/conf3/ghc/inplace/mingw/bin/ar.exe: creating .build/stage1/rts/build/libHSrts.a
    C:/Neil/ghc/conf3/ghc/inplace/mingw/bin/ar.exe: unable to rename '.build/stage1/rts/build/libHSrts.a'; reason: No such file or directory

And checking that assertion:

    $ ls .build/stage1/rts/build/*.a
    .build/stage1/rts/build/libCffi-6.a  .build/stage1/rts/build/libHSrts_thr.a

Rerunning just that gave:

    $ shake-build/build.bat --configure=--enable-tarballs-autodownload -j .build/stage1/rts/build/libHSrts.a
    | Run configure (--enable-tarballs-autodownload)...
    ... seemed to almost be starting from scratch ...

Which was a bit weird. I complete configure. Why is it rerunning configure etc?

That run ended up failing with:

    build: .build/stage0/compiler/package-data.mk: openFile: does not exist (No such file or directory)

But that file does exist...

So I did a `clean` and tried again. This time it worked. I've got failures to build libHSrts.a before, in roughly the same place, so I thought it worth raising.

**Comment by snowleopard** [comment] 2016-02-04 12:03
I've never seen this `libHSrts.a` failure before. Will try to reproduce on my machine.

> Why is it rerunning configure etc?

Because you asked it to with `--configure=--enable-tarballs-autodownload`. Remember: this is currently a direct command to the build system to rerun `configure`. It is supposed to be used only on the first run. The right way to build this file only is to run `shake-build/build.bat -j .build/stage1/rts/build/libHSrts.a`.

**Comment by ndmitchell** [comment] 2016-02-04 12:08
Yep, I figured out the configure thing, and ticketed that separate as #204. I'll do some soak test builds, clean/rebuild, and see what I get.

**Comment by snowleopard** [comment] 2016-02-06 19:18
Not sure what's going on. Here is how I invoke `Ar` when `@file` is supported:
```haskell
useAtFile :: FilePath -> [String] -> [String] -> Action ()
useAtFile path flagArgs fileArgs = withTempFile $ \tmp -> do
    writeFile' tmp $ unwords fileArgs
    cmd [path] flagArgs ('@' : tmp)
```
I may be running into the problem of lazy `writeFile'`, but I don't understand how this leads to the reported errors. Looking at the error message, the command was
```
Command: C:/Neil/ghc/conf3/ghc/inplace/mingw/bin/ar.exe q .build/stage1/rts/build/libHSrts.a @C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\msys2-20150512\tmp\extra-file-504133661-1694121724
```
which seems fine to me.

I've no idea why `Ar` needs to do any intermediate renaming of `.build/stage1/rts/build/libHSrts.a` that is mentioned in `stderr` and appears to be the cause of the error.
```
Stderr:
C:/Neil/ghc/conf3/ghc/inplace/mingw/bin/ar.exe: creating .build/stage1/rts/build/libHSrts.a
C:/Neil/ghc/conf3/ghc/inplace/mingw/bin/ar.exe: unable to rename '.build/stage1/rts/build/libHSrts.a'; reason: No such file or directory
```
Maybe this is the way `Ar` complains about empty `@file` (due to lazy `writeFile'`)?

**Comment by ndmitchell** [comment] 2016-02-06 19:47
`writeFile` is not lazy, only `readFile`, so that's not the problem. I'll keep soak testing and if it doesn't reproduce we can close as not being that common, or perhaps being an artefact of something else.

**Comment by snowleopard** [comment] 2016-02-06 21:37
> writeFile is not lazy, only readFile, so that's not the problem

Ah, indeed.

I failed to reproduce. I suspect that `withTemp` is somehow related, but can't quite figure it out.

**Comment by ndmitchell** [comment] 2016-02-06 22:31
GHC's temp file functions are buggy. Shake's have been stress tested a lot. But it's a tricky race condition prone problem, so I should test some more.

**Comment by bgamari** [comment] 2016-02-08 15:34
> GHC's temp file functions are buggy. 

This is quite concerning to hear. @ndmitchell Could you open a GHC bug for this if you have a test case (or even a rough idea of where the issue may be)?

**Comment by ndmitchell** [comment] 2016-02-08 16:55
My memory is that I already did raise a bug, but I'll double check...

**Comment by thomie** [comment] 2016-02-08 17:28
https://ghc.haskell.org/trac/ghc/ticket/10731

**Comment by ndmitchell** [comment] 2016-02-08 19:51
Thanks @thomie, yes, that was what I was thinking of. Test harnesses and a fully implemented workaround, what more could you want :)

**Comment by snowleopard** [comment] 2016-02-09 16:29
Got hit by this today, for the first time I think.

@ndmitchell Since we only use `withTempFile` a couple of times in the whole build system, perhaps, we can just avoid them at all and keep temporary files among build artefacts? A bit inelegant, but doesn't seem to be a big issue.

**Comment by ndmitchell** [comment] 2016-02-09 16:33
We are using Shake's temporary files, which are super robust, and in this case just keyed off an IORef in process so will never fail. It's unlikely to be that, or at least obviously and simply that...

**Comment by snowleopard** [comment] 2016-02-09 16:39
Ah, I somehow assumed this issue is related to the GHC bug. Sorry for the noise. Still no idea how to properly fix this (apart from trying to get rid of temporary files).

**Comment by ndmitchell** [comment] 2016-02-09 16:46
If you rm the file then rebuild in a loop, does that trigger it? Without the ability to trigger hard to experiment with what is the culprit.

**Comment by ndmitchell** [comment] 2016-03-04 15:21
I've not seen this in a lot of soak testing. Shall we hopefully assume its gone?

**Comment by snowleopard** [comment] 2016-03-04 16:35
Yep, let me close this.

**Closed by snowleopard** 2016-03-04 16:35 UTC
Labels: bug, Windows
