### ISSUE TITLE
Failure to install without make on PATH

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#211] opened 2016-03-03 12:07 UTC
I built a new VM, with very few tools on it, and tried to compile GHC using only Stack. I got the error below. I guess something that it wanted to detect was the empty string? Shouldn't that be an error? I didn't have make installed, which I assume is the issue.

![virtualbox_ie11 - win10_03_03_2016_12_01_11](https://cloud.githubusercontent.com/assets/1651197/13493737/c2011b94-e137-11e5-9df8-061fa2352742.png)

**Comment by ndmitchell** [comment] 2016-03-03 12:08
(And no, I have not yet figured out how to copy out of my VM...)

**Comment by snowleopard** [comment] 2016-03-03 12:12
Sounds like a bug indeed.

Can you find a line like `Executable found: make => D:/msys/usr/bin/make.exe` in the build log? This will confirm that an empty path was found for `make` for some reason.

**Comment by snowleopard** [comment] 2016-03-03 12:15
Also, could you check `system.config`? I expect it to have a line like `make = make` set by `configure`.

**Comment by ndmitchell** [comment] 2016-03-03 12:23
I see:

    make                        =

I can't find the executable found line in the log, but that may be just me missing it. I assume the system.config problem is the underlying cause, and you should just give a better error?

**Comment by snowleopard** [comment] 2016-03-03 12:26
@ndmitchell Agreed. A missing executable in `system.config` should be an error. Will fix this today.

**Comment by ndmitchell** [comment] 2016-03-03 12:27
@snowleopard - be careful, some like hscolour are optional.

**Comment by snowleopard** [comment] 2016-03-03 12:40
@ndmitchell Hmm, indeed... Looks like we have a distinction between `essential` and `optional` builders. Most builders are essential; `hscolour` is the only optional one I can remember.

**Comment by snowleopard** [comment] 2016-03-04 01:53
@ndmitchell Should be fixed now.

During testing I got hit by #206! Here is exactly what I did:
* I run a successful build with `./build.bat -j4 --flavour=quick`.
* Opened `system.config` and set `make = `.
* Restarted `./build.bat -j4 --flavour=quick`.
* This led to the following error, as intended:
```
Builder 'make' is not specified in system.config file. Cannot proceed without it.
```
* Opened `system.config` and set `make = make`, as before.
* Restarted `./build.bat -j4 --flavour=quick`.
* The build finished and reported the elusive error (`echo $?` said `1`):
```
build: .build/stage2/utils/ghctags/package-data.mk: openFile: does not exist (No such file or directory)
```

Can you reproduce this? If yes, hopefully this will shed some light on #206.

**Comment by snowleopard** [comment] 2016-03-04 10:36
Being explicit about optional builders uncovers interesting things. OS X instance of Travis failed with:
```
Builder 'objdump' is not specified in system.config file. Cannot proceed without it.
```
Apparently, no `objdump` is provided by `configure` on OS X. However, the build system did work on OS X somehow, so it clearly wasn't essential. Shall we consider it optional on other platforms as well? Or shall we change the `isOptional` signature to `Builder -> Action Bool` and make the result platform-specific?

**Comment by ggreif** [comment] 2016-03-04 10:46
Darwin (and transitively Mac OS X) has no `objdump`, but `otools`
(IIRC) instead. So the optional dependencies should be
platform-specific.

**Comment by snowleopard** [comment] 2016-03-04 11:13
@ggreif Many thanks! But then the question is: do we have to use `otools` (or something like that) instead of `objdump` on Darwin? Another way of putting this: is `objdump/otools` really optional on Darwin or perhaps we just got lucky the build system worked without `objdump/otools` previously?

**Comment by ggreif** [comment] 2016-03-04 16:53
I believe objdump/otools is only needed in the cross-compilation case.
Unless it is used for the TABLE_NEXT_TO_CODE hack. Where do these
tools appear in the makefiles?

**Comment by snowleopard** [comment] 2016-03-04 17:12
@ggreif Here is the only example from the new build system: https://github.com/snowleopard/shaking-up-ghc/blob/master/src/Settings/Builders/DeriveConstants.hs#L26-L27.
```haskell
        , specified Objdump ? mconcat [ arg "--objdump-program"
                                      , arg =<< getBuilderPath Objdump ]
```
Here it is clear that `Objdump` is optional: if it is `specified` it is passed as an argument to `DeriveConstants` builder. 

Another example can be found in `build-package-way.mk` in the old build system.

**Comment by ggreif** [comment] 2016-03-04 23:16
@snowleopard yep, looks like `objdump` is only needed on OpenBSD and AIX. These have a problematic `nm`.

**Comment by snowleopard** [comment] 2016-03-05 13:20
@ggreif Thanks! I made `objdump` optional for now, and added a `TODO` to add support for platform-specific builders. Not sure I can do it right now because I don't have access to OpenBSD/AIX machines to reliably test this feature.

**Closed** 2016-03-05 20:50 UTC
